import Head from "next/head";
import Image from "next/image";
import logo from "../public/img/Transimple - logo.svg";
import { Inter } from "@next/font/google";
import { Nav } from "../components/Nav";
import { Box } from "../components/Box";
import { motion } from "framer-motion";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Transimple</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={inter.className}>
        <section className="flex flex-col justify-center h-screen bg-home">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ type: "spring", stiffness: 400, damping: 17 }}
            className=" items-center justify-center absolute top-0 hidden sm:flex "
          >
            <Nav />
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 70 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ type: "spring", stiffness: 400, damping: 17 }}
          >
            <div className="flex items-center justify-center sm:mb-10">
              <Image
                src={logo}
                className=" w-36  md:w-56"
                draggable="false"
                alt="Transimple"
              />
            </div>

            <div className="flex items-center justify-center">
              <Box />
            </div>
          </motion.div>
        </section>
      </main>
    </>
  );
}
